version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      npm-deps:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      composer-deps:
        update-types:
          - "minor"
          - "patch"
